### ISSUE TITLE
Possibility for workers to process only a given list of types of jobs

### ISSUE THREAD

**Issue by koraykoska** [reswifq/reswifq#2]
## Problem

Currently a worker automatically moves all jobs from `queue:pending:medium` to `queue:processing` and tries to process them regardless of their type.

I have a system which has different workers on different machines, which means only certain types of jobs should be processed on a given machine and others on other machines.

If the job type is not in the Reswifq `jobMap` an error will be [thrown](https://github.com/reswifq/reswifq/blob/a4764bc0bb8f56675aaab691877b344bfb0131c5/Sources/Reswifq/Reswifq.swift#L255).

Actually there is currently no possibility to process only certain types of jobs as there are no special keys with the job name (e.g.: `queue:pending:medium:JobName`).

## Proposed solution

We could make an optional possibility to order jobs by job type so the worker can also be specialized to perform only certain types of jobs.

The key of the lists would look a little bit like that:

`queue:pending:medium:JobName`

Where `JobName` is the job type which is currently stored in the objects as the `type`.

The worker can then get only certain types of jobs and have different queues which are specifically for a single job type.

All of this can be done without a breaking change. We can simple allow grouping jobs but don't require it.

What do you think about that?

**Comment by valeriomazzeo** [comment]
Hi @Ybrin,

Not mapping a job type for a specific worker would be a perfect valid solutIon, as the error thrown is caught and logged and it doesn't stop the thread execution.

Unfortunately, at that stage the job has already been moved to the `processing` queue meaning that if it's picked up by a worker that didn't know how to deserialise it then it won't be available to be processed by a valid worker anymore. It is also not possible to dequeue the job only if valid, because to know that, the job has to be dequeued first (chicken and egg issue).

You have proposed an interesting solution, unfortunately dequeuing from multiple queues using redis natively, in a reliable way, has proven to be more complicated than expected which is the reason why at the moment priority queues are not supported.

Note: sidekiq has a similar issue ( https://github.com/antirez/redis/issues/1785 ) that they have worked around at performance expenses.

After analysing the problem, I came to the conclusion that, in my opinion, the best solution would be to connect each Worker to a different queue.

Since you can have many queues connecting to different databases shared on the same redis instance, you can then enqueue all the jobs of a certain type in the same queue, and have each worker consume from a different queue.

Configuration shouldn't be anymore complicated than the solution you have proposed. 

Also, `reswifc` is flexible enough to allow you to use the same process to monitor multiple queues, this is something I didn't think at all when I first designed it, but it would work:

```swift
let reswifc = Reswifc(processes: [
    Reswifc.Monitor(queue: queue, interval: 5, maxRetryAttempts: 3),
    Reswifc.Scheduler(queue: queue, interval: 1)
    ...
    You can add here any number of monitors / schedulers pointing to different queues
    ])

reswifc.run()
```
 

Thoughts?

**Comment by koraykoska** [comment]
Hi @valeriomazzeo 

Thank you for your quick response.

You are right. The main problem is that the jobs are moved to the `queue:processing` list. This means if I have one specific worker for each job type, I can't work with a single database as this would lead to unfinished jobs staying in the `processing` queue forever.

If I understand your solution correctly, we should just connect each worker to a specific database number on the redis side and have multiple instances of `Reswifq` which are exactly responsible for one job type.

If this is what you mean, I don't understand why having multiple queues on one database would be more inefficient than having one queue per database. In either way you need one instance of `Reswifq` to handle enqueuing and dequeuing for exactly one job type.

I understand that this is not necessary for people who don't want to have different workers for different job types but it would make sense if you have many jobs and don't want to use a new database number for every new job type.

I never used sidekiq so I don't really know how they solved this problem. Would this be a viable solution for reswifq or do you think it is not worth it? If not I will just go with different databases for different job types for now...

**Comment by valeriomazzeo** [comment]
I don't see any difference in terms of efficiency, in fact I suppose both ways would work with similar performances. Perhaps, with separate databases you achieve a better separation of concerns between jobs with different types.

In the end, with the current system, it boils down to having to do something like this:

```swift
// Your service
emailQueue.enqueue(myJob)
smsQueue.enqueue(anotherJob)

// Workers
let emailWorker = Worker(queue: emailQueue)
let smsWorker = Worker(queue: smsQueue)
```

Your proposed solution, perhaps could have the same interface for enqueuing a job, but when dequeuing, it will have to have an additional parameter that specifies the type.

Internally, the only way I see it working, is if in fact, there is one queue per type (as I think you have already suggested). This would be ok for this specific use case, because workers will be dequeuing jobs always from the same queue, but in all other scenarios (1 worker for many job types), it won't be possible to have redis atomically dequeuing from multiple queues (see https://github.com/antirez/redis/issues/1785). This is possibly the only problem I can think of, that could prevent this from being implemented.

I would definitely exclude, having different implementations of the underlying queue system for the two different scenarios, because that would mean that when you switch from one system to another the persisted data won't be compatible.

For the above reasons, I believe that the best approach is to split different jobs in multiple databases / or redis instances. 

In my opinion, the beauty of the current implementation is that all of this is completely transparent and flexible. For example, if you don't like the idea of keeping around multiple queue references in your scheduler, you could extend one of the provided Redis client to redirect the enqueuing operation to the correct database / instance based on the job type.

Having said that, pull requests are welcome :)
