### ISSUE TITLE
How do I run reswifq tests?

### ISSUE THREAD

**Issue by krazyjakee** [reswifq/reswifq#6]
How do I setup this project to be able to run tests?

Currently I get `No such module 'SwiftRedis' and I don't think you want that in the library dependencies.

**Comment by valeriomazzeo** [comment]
Are you trying to run Reswifq tests? 

If so, in order to run, Reswifq tests need a concrete implementation of a `RedisClient` and a running `Redis Server`.

If you'll notice, the current project setup has two Swift Package Manager files:
- https://github.com/reswifq/reswifq/blob/master/Package.swift
- https://github.com/reswifq/reswifq/blob/master/.Package.test.swift

When Travis-CI runs, `.Package.test.swift` is renamed to `Package.swift` so that test dependencies can be installed and test executed correctly. See https://github.com/reswifq/reswifq/blob/master/.travis.yml#L20 .

**Comment by krazyjakee** [comment]
Perfect, thank you very much :)
